audio:
  chunk_size: 130560
  dim_f: 1024
  dim_t: 256
  hop_length: 512
  n_fft: 2048
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.001

model:
  act: gelu
  bottleneck_factor: 4
  growth: 128
  norm: InstanceNorm
  num_blocks_per_scale: 2
  num_channels: 128
  num_scales: 5
  num_subbands: 4
  scale:
  - 2
  - 2

training:
  batch_size: 2
  gradient_accumulation_steps: 3
  grad_clip: 0
  instruments:
  - similarity
  - difference
  lr: 1.0
  patience: 15
  reduce_factor: 0.95
  target_instrument: similarity
  num_epochs: 1000
  num_steps: 2235
  q: 0.95
  coarse_loss_clip: true
  ema_momentum: 0.999
  optimizer: prodigy
  other_fix: false # it's needed for checking on multisong dataset if other is actually instrumental
  use_amp: true # enable or disable usage of mixed precision (float16) - usually it must be true

augmentations:
  enable: true # enable or disable all augmentations (to fast disable if needed)
  loudness: true # randomly change loudness of each stem on the range (loudness_min; loudness_max)
  loudness_min: 0.5
  loudness_max: 1.5
  
  all:
    channel_shuffle: 0.5 # Set 0 or lower to disable
    random_inverse: 0.01 # inverse track (better lower probability)
    random_polarity: 0.5 # polarity change (multiply waveform to -1)
    mp3_compression: 0.0
    mp3_compression_min_bitrate: 32
    mp3_compression_max_bitrate: 320
    mp3_compression_backend: "lameenc"
    pitch_shift: 0.1
    pitch_shift_min_semitones: -3
    pitch_shift_max_semitones: 3
    seven_band_parametric_eq: 0.5
    seven_band_parametric_eq_min_gain_db: -6
    seven_band_parametric_eq_max_gain_db: 6
    tanh_distortion: 0.2
    tanh_distortion_min: 0.1
    tanh_distortion_max: 0.5

similarity:
    gaussian_noise: 0.1
    gaussian_noise_min_amplitude: 0.001
    gaussian_noise_max_amplitude: 0.015

difference:
    pedalboard_reverb: 0.01
    pedalboard_reverb_room_size_min: 0.1
    pedalboard_reverb_room_size_max: 0.9
    pedalboard_reverb_damping_min: 0.1
    pedalboard_reverb_damping_max: 0.9
    pedalboard_reverb_wet_level_min: 0.1
    pedalboard_reverb_wet_level_max: 0.5
    pedalboard_reverb_dry_level_min: 0.5
    pedalboard_reverb_dry_level_max: 0.9
    pedalboard_reverb_width_min: 0.3
    pedalboard_reverb_width_max: 1.0

inference:
  batch_size: 1
  dim_t: 256
  num_overlap: 4
